version: "3.8"

services:
  traefik:
    restart: always
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "3000:80"
      - "3001:443"
      - "3002:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
  
  app:
    restart: always
    image: playground-kratos
    command: ./playground-kratos -conf ./configs
    labels:
      # - traefik.http.routers.home.rule=Host(`deno-mfe.localhost`) && PathPrefix(`/shop`)
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`playground.localhost`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.service=app
      - traefik.http.services.app.loadbalancer.server.port=8000
    # environment:
    #   - APP_NAME=Home
    # volumes:
    #   - ./app:/app

networks:
  local_network:
    driver: bridge