server:
  http:
    addr: "0.0.0.0:2000"
    timeout: 1s
  grpc:
    addr: "0.0.0.0:2100"
    timeout: 1s
data:
  database:
    driver: "postgres"
    host: "192.168.1.9"
    port: 5432
    user: "root"
    password: "11234566"
    db_name: "testdb"

  redis:
    addr: "192.168.1.9:6378"
    read_timeout: 0.2s
    write_timeout: 0.2s
